### PR TITLE
Basic package.json

### PR DESCRIPTION
**Pull request by PhearZero**
For all the browserify users out there!

### CODE REVIEW

**Comment by jmeisel** [comment]
Thanks for the PR.  Our main person who reviews and merges PRs may be out of the office for a few days but we will review ASAP.

**Comment by PhearZero** [comment]
Thank you, It's not a biggie just a package.json for browserify. I'll be messing around with it and I'll let you guy's know what I run into

**Comment by jontonsoup** [comment]
@PhearZero i think this is missing exports for nodejs as well. including a `package.json` will confuse people if it doesn't work as expected.

**Comment by bureauofthecensus** [comment]
This pull request have conflicts with master branch. 
Please re-submit pull request.

**Pull request closed without merging**
