### PR TITLE
Latest city SDK for Decennial.

### PR DESCRIPTION
**Pull request by PureLeaf**
This is the decennial module for the City SDK

Signed-off-by: David Lee <david.lee@census.gov>

### CODE REVIEW

**Comment by johnson-tor-boozallen** [comment]
Hey David -

I have a history question.  Why did we implement the decennial as a separate module instead of integrate with the main census module?

[base email logo]

Tor N. Johnson
Associate
Desk: 571-346-4331
Mobile: 703-862-5790
Johnson_tor@bah.com<mailto:Johnson_tor@bah.com>

**Comment by johnson-tor-boozallen** [comment]
We'll need to update this code to function similar to the newer structure the census module & core changes in #198.

**Comment by PureLeaf** [comment]
Hi Tor,


Happy New Year.


The concept behind this was that there would be a module for every survey while in development and a final module that includes everything at the end.


For the sake of development it was easier to develop them separately.


The modules are similar enough that most of the modules will be reusing the same code, however its the differences that that will determine how easy it is to update.


Say for example if the Census updated the dataset for decennial.  It becomes exponentially more difficult to wade through 10k+ lines of code for a centralized module rather than focusing on a stand alone 2k line module exclusively for the decennial?  With a dozen or so datasets to cover, thats a huge module.  A stand alone ACS module also has the benefit for allow others who are making modules for their own use to see how its done more easily.


Eventually, the idea was to also combine the separate modules by including them in the main module once all the survey datasets were done.  However, it made sense to keep them separate while rapidly developing all the surveys first.  This may help users understand what's being added during each iteration as well as allow users who are just using the ACS module to not have to constantly update their module if a new survey module is released each week.



Again, I'll leave it up to decide how to proceed.



As for the decennial module, feel free to update or discard and develop your own as you see fit.  My development schedule is full for the new two weeks or so, but I can definitely make the update to match the new structure and core changes after that.




David Lee

CAT Support Team, Booz Allen Hamilton

Android Developer

Chief Technology Office

U.S. Census Bureau

david.lee@census.gov<mailto:david.lee@census.gov>

lee_david@bah.com<mailto:lee_david@bah.com>

Cell (703) 597-8217


________________________________

**Comment by johnson-tor-boozallen** [comment]
Hi David -

I can see the logic of that approach.  Longer term, it will be simpler for users who aren't experts in the different census datasets if we have a single integrated census module.  For many applications they likely will not understand the differences between the modules.  We can also minimize library weight / code replication by combining the ACS and SF1 datasets into a single module as most of the code is identical (even though we do face somewhat increased complexity as you point out).


[base email logo]

Tor N. Johnson
Associate
Desk: 571-346-4331
Mobile: 703-862-5790
Johnson_tor@bah.com<mailto:Johnson_tor@bah.com>

**Pull request closed without merging**
